### ISSUE TITLE
Issue 5: Promoting on the big group repository. 

### ISSUE THREAD

**Issue by ShreyasGoyal** [csci3250-2019/project-team-j#33]
Who is going to add the link to csci3250-2019.github.io repository?

**Comment by NHT0701** [comment]
I can help you out with this

**Comment by ShreyasGoyal** [comment]
ok, thanks. 
open the issues folder, and read the instructions in issue 5

**Comment by NHT0701** [comment]
I just add the following line in readme.md on the io page, however the edit isn't shown as I wish, maybe it needs permission??
* [Team J](https://csci3250-2019.github.io/project-team-j/ 'Team-J')

**Comment by ShreyasGoyal** [comment]
Yes, a review is required.
"Edit the file to add a link of your team, and request for review from @chuckjee"

**Comment by NHT0701** [comment]
oic , due to unknown reason, I couldn't directly ask for a review from chukjee via reviewers button, so I write a comment a @ chukjee there, hope it will work~ xd

**Comment by NHT0701** [comment]
DONE ~
